services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: discussions_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: "8080"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  discussion_api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://fastapi_user:8080@db:5432/discussions_db
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["uvicorn", "DiscussionDigestAPI:app", "--host", "0.0.0.0", "--port", "8000"]

  db_api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://fastapi_user:8080@db:5432/discussions_db
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8001:8001"
    command: ["uvicorn", "DBConnectionAPI:app", "--host", "0.0.0.0", "--port", "8001"]

  ecr_api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://fastapi_user:8080@db:5432/discussions_db
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8002:8002"
    command: ["uvicorn", "ECRConnectionAPI:app", "--host", "0.0.0.0", "--port", "8002"]

  supplier_api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://fastapi_user:8080@db:5432/discussions_db
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8003:8003"
    command: ["uvicorn", "SupplierConnectionAPI:app", "--host", "0.0.0.0", "--port", "8003"]

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - discussion_api
      - db_api
      - ecr_api
      - supplier_api
    ports:
      - "8080:80"



volumes:
  pgdata:

